-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT programme.ID AS ENTITY_ID, programme.NAME AS ENTITY_NAME,
       programme.REGION, programme.CATEGORY, programme.RISK_TIER, programme.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.DISBURSEMENT_COUNT) AS DISBURSEMENT_COUNT,
       SUM(observation.VALUE_IDR) AS VALUE_IDR,
       SUM(observation.DELAYED_COUNT) AS DELAYED_COUNT,
       SUM(observation.ESCALATED_COUNT) AS ESCALATED_COUNT,
       SUM(observation.SLA_BREACHED) AS SLA_BREACH_COUNT,
       SUM(observation.REVIEW_DUE) AS REVIEW_DUE,
       SUM(observation.REVIEW_COMPLETED) AS REVIEW_COMPLETED,
       100.0 * (SUM(observation.DISBURSEMENT_COUNT) - SUM(observation.DELAYED_COUNT)) / NULLIF(SUM(observation.DISBURSEMENT_COUNT), 0) AS ON_TIME_RATE_PCT,
       100.0 * SUM(observation.ESCALATED_COUNT) / NULLIF(SUM(observation.DELAYED_COUNT), 0) AS ESCALATION_SHARE_PCT,
       100.0 * SUM(observation.REVIEW_COMPLETED) / NULLIF(SUM(observation.REVIEW_DUE), 0) AS REVIEW_COMPLIANCE_PCT,
       AVG(observation.TRANSFER_REJECT_PCT) AS AVG_TRANSFER_REJECT_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.PROGRAMME_DAILY observation
JOIN RAW.PROGRAMMES programme ON programme.ID = observation.ENTITY_ID
GROUP BY programme.ID, programme.NAME, programme.REGION, programme.CATEGORY, programme.RISK_TIER, programme.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(DISBURSEMENT_COUNT) AS DISBURSEMENT_COUNT, SUM(VALUE_IDR) AS VALUE_IDR,
       SUM(DELAYED_COUNT) AS DELAYED_COUNT, SUM(ESCALATED_COUNT) AS ESCALATED_COUNT,
       100.0 * SUM(ESCALATED_COUNT) / NULLIF(SUM(DELAYED_COUNT), 0) AS ESCALATION_SHARE_PCT
FROM RAW.PROGRAMME_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.DELAY_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT DELAY_REASON, SUM(DELAYED_COUNT) AS DELAYED_COUNT,
       SUM(ESCALATED_COUNT) AS ESCALATED_COUNT,
       SUM(SLA_BREACHED) AS SLA_BREACH_COUNT,
       SUM(VALUE_IDR) AS EXPOSED_VALUE_IDR,
       100.0 * SUM(ESCALATED_COUNT) / NULLIF(SUM(DELAYED_COUNT), 0) AS ESCALATION_SHARE_PCT
FROM RAW.PROGRAMME_DAILY
WHERE DELAYED_COUNT > 0
GROUP BY DELAY_REASON;

CREATE DYNAMIC TABLE CURATED.CHANNEL_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT CHANNEL, IS_DIGITAL, SUM(DONATION_COUNT) AS DONATION_COUNT,
       SUM(COLLECTED_IDR) AS COLLECTED_IDR,
       100.0 * SUM(COLLECTED_IDR) / NULLIF(SUM(SUM(COLLECTED_IDR)) OVER (), 0) AS SHARE_PCT,
       SUM(COLLECTED_IDR) / NULLIF(SUM(DONATION_COUNT), 0) AS AVG_DONATION_IDR
FROM RAW.DONOR_CHANNEL_DAILY
GROUP BY CHANNEL, IS_DIGITAL;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(DISBURSEMENT_COUNT) AS DISBURSEMENTS, SUM(DELAYED_COUNT) AS DELAYS,
         SUM(ESCALATED_COUNT) AS ESCALATED, SUM(SLA_BREACHED) AS BREACHES, SUM(VALUE_IDR) AS VALUE_IDR,
         SUM(REVIEW_DUE) AS REVIEW_DUE, SUM(REVIEW_COMPLETED) AS REVIEW_COMPLETED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.PROGRAMME_DAILY
), book AS (SELECT COUNT(*) AS PROGRAMME_COUNT FROM RAW.PROGRAMMES),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.PROGRAMME_DOCUMENTS
), channels AS (
  SELECT SUM(COLLECTED_IDR) AS COLLECTED_IDR,
         100.0 * SUM(IFF(IS_DIGITAL, COLLECTED_IDR, 0)) / NULLIF(SUM(COLLECTED_IDR), 0) AS DIGITAL_SHARE_PCT
  FROM RAW.DONOR_CHANNEL_DAILY
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'On-Time Disbursement Rate' AS TITLE,
         100.0 * (DISBURSEMENTS - DELAYS) / NULLIF(DISBURSEMENTS, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Delay Cases', DELAYS, '' FROM observations
  UNION ALL SELECT 3, 'Escalated to Programme Review', ESCALATED, '' FROM observations
  UNION ALL SELECT 4, 'Escalation Rate', 100.0 * ESCALATED / NULLIF(DELAYS, 0), '%' FROM observations
  UNION ALL SELECT 5, 'Beneficiary Notice SLA Breaches', BREACHES, '' FROM observations
  UNION ALL SELECT 6, 'Disbursed Value (IDR B)', VALUE_IDR / 1e9, '' FROM observations
  UNION ALL SELECT 7, 'Disbursements Scheduled', DISBURSEMENTS, '' FROM observations
  UNION ALL SELECT 8, 'Field Verification Compliance', 100.0 * REVIEW_COMPLETED / NULLIF(REVIEW_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Programmes Monitored', PROGRAMME_COUNT, '' FROM book
  UNION ALL SELECT 10, 'Programme File Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 11, 'Programme Documents Pending', PENDING, '' FROM documents
  UNION ALL SELECT 12, 'Collections (IDR B)', COLLECTED_IDR / 1e9, '' FROM channels
  UNION ALL SELECT 13, 'Digital Channel Share', DIGITAL_SHARE_PCT, '%' FROM channels
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                WHEN metrics.SORT_ORDER = 1 THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 2), '990.00'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.DELAY_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.CHANNEL_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
