-- Generated from generator/demo_specs/aws-indonesia-islamic-finance-zakat.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-indonesia-islamic-finance-zakat
-- This is the schema that is actually deployed for ID_ISLAMIC_FINANCE_ZAKAT.

-- Alerts fire on the bottom tail of Distribution Efficiency
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_DISTRIBUTION_EFFICIENCY) AS T
  FROM RAW.COLLECTIONS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_DISTRIBUTION_EFFICIENCY <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_DISTRIBUTION_EFFICIENCY), 2) AS AVG_DISTRIBUTION_EFFICIENC,
  ROUND(AVG(f.KPI_COLLECTION_GROWTH), 2) AS AVG_COLLECTION_GROWTH
FROM RAW.COLLECTIONS f
JOIN RAW.IMPACT_REPORTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_DISTRIBUTION_EFFICIENCY), 2) AS AVG_DISTRIBUTION_EFFICIENC,
  ROUND(AVG(f.KPI_COLLECTION_GROWTH), 2) AS AVG_COLLECTION_GROWTH
FROM RAW.COLLECTIONS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_DISTRIBUTION_EFFICIENCY) AS KPI_DISTRIBUTION_EFFICIENCY, AVG(KPI_COLLECTION_GROWTH) AS KPI_COLLECTION_GROWTH FROM RAW.COLLECTIONS),
     en AS (SELECT SUM(KPI_ZAKAT_COLLECTED_YTD) AS KPI_ZAKAT_COLLECTED_YTD, SUM(KPI_BENEFICIARIES_REACHED) AS KPI_BENEFICIARIES_REACHED, SUM(KPI_POVERTY_ALLEVIATION) AS KPI_POVERTY_ALLEVIATION, SUM(KPI_EDUCATION_SCHOLARSHIPS) AS KPI_EDUCATION_SCHOLARSHIPS, SUM(KPI_HEALTHCARE_SUPPORT) AS KPI_HEALTHCARE_SUPPORT FROM RAW.IMPACT_REPORTS)
  SELECT 1 AS SORT_ORDER, 'Zakat Collected (YTD)' AS TITLE, KPI_ZAKAT_COLLECTED_YTD AS VALUE_NUM, 'Rp' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_ZAKAT_COLLECTED_YTD) / 1000000000000), 1) AS DECIMAL(38,1))) || 'T' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Beneficiaries Reached' AS TITLE, KPI_BENEFICIARIES_REACHED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_BENEFICIARIES_REACHED) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Distribution Efficiency' AS TITLE, KPI_DISTRIBUTION_EFFICIENCY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DISTRIBUTION_EFFICIENCY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Collection Growth' AS TITLE, KPI_COLLECTION_GROWTH AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_COLLECTION_GROWTH)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Poverty Alleviation' AS TITLE, KPI_POVERTY_ALLEVIATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_POVERTY_ALLEVIATION) / 1000000), 1) AS DECIMAL(38,1))) || 'M' || ' ' || 'families' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Education Scholarships' AS TITLE, KPI_EDUCATION_SCHOLARSHIPS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_EDUCATION_SCHOLARSHIPS) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Healthcare Support' AS TITLE, KPI_HEALTHCARE_SUPPORT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_HEALTHCARE_SUPPORT) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
