-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Zakat & Waqf Management
-- ============================================================================
USE DATABASE ZAKAT_MANAGEMENT;
USE SCHEMA ML;

-- ML.FORECAST: COLLECTION_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.COLLECTION_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.COLLECTION_DASHBOARD'),
  SERIES_COLNAME => 'CHANNEL',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.COLLECTION_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.COLLECTION_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

