-- ============================================================================
-- 99_RESET.SQL — Reset Zakat & Waqf Management to clean demo state
-- ============================================================================
USE DATABASE ZAKAT_MANAGEMENT;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_COLLECTIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_COLLECTIONS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_IMPACT SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.COLLECTION_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.DISTRIBUTION_EQUITY REFRESH;
ALTER DYNAMIC TABLE CURATED.DONOR_SEGMENTATION REFRESH;
ALTER DYNAMIC TABLE CURATED.IMPACT_METRICS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ZAKAT_MANAGEMENT.RAW.MUZAKKI → 2000000
-- SELECT COUNT(*) FROM ZAKAT_MANAGEMENT.RAW.COLLECTIONS → 5000000
-- SELECT COUNT(*) FROM ZAKAT_MANAGEMENT.RAW.MUSTAHIK → 500000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_UPDATE_IMPACT RESUME;
ALTER TASK IF EXISTS APP.TASK_FORECAST_COLLECTIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_COLLECTIONS RESUME;
